/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Czy;
import model.Yhqs;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;


public class AddCzyAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm f = (DynaValidatorForm) form;
		String username = f.getString("username");
		String password = f.getString("password");
		int qsno = Integer.parseInt(f.getString("yhqs"));
		Yhqs yhqs = mgr.findYhqsByQsno(qsno);
		
		Czy c = new Czy();
		c.setUsername(username);
		c.setPassword(password);
		c.setYhqs(yhqs);
		mgr.save(c);
		return mapping.findForward("viewallczy");
	}
}