/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;

import model.Kh;

/** 
 * MyEclipse Struts
 * Creation date: 03-15-2009
 * 
 * XDoclet definition:
 * @struts.action path="/addKh" name="addKhForm" input="/form/addKh.jsp" scope="request" validate="true"
 * @struts.action-forward name="addKhSuccess" path="/success/addKhSuccess.jsp"
 */
public class AddKhAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		DynaValidatorForm addKhForm = (DynaValidatorForm) form;
		
		String yd = request.getParameter("yd");		
		System.out.println(yd);
		request.setAttribute("yd", yd);
		Kh k = new Kh();
		k.setKhmc(addKhForm.getString("khmc"));
		String khlxno = addKhForm.getString("khlx");
		k.setKhlx(mgr.findKhlxByKxno(khlxno));
		k.setKhxb(addKhForm.getString("khxb"));
		k.setZjlx(addKhForm.getString("zjlx"));
		k.setZjbh(addKhForm.getString("zjbh"));
		k.setDz(addKhForm.getString("dz"));
		HttpSession session=request.getSession();
		session.setAttribute("location1", "预定管理");
		session.setAttribute("location2", "预定登记");
		
		System.out.println(addKhForm.getString("khxb") + "," + addKhForm.getString("zjbh"));
		request.setAttribute("kh", k);
		mgr.addKh(k);
		return mapping.findForward("addKhSuccess");
	}
}