/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Czy;
import model.Fj;
import model.Kh;
import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;

/** 
 * MyEclipse Struts
 * Creation date: 03-20-2009
 * 
 * XDoclet definition:
 * @struts.action path="/addRz" name="addRzForm" input="/form/addRz.jsp" scope="request" validate="true"
 * @struts.action-forward name="addRzSuccess" path="/success/addRzSuccess.jsp"
 */
public class AddRzAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm addRzForm = (DynaValidatorForm) form;// TODO Auto-generated method stub
		
//		HttpSession session = request.getSession();
		int userid = (Integer) request.getSession().getAttribute("userId");
		Czy c = mgr.get(userid);
		
		Rz r = new Rz();
		Kh k = mgr.findKhByKhno(Integer.parseInt(request.getParameter("khno")));
		Fj f = mgr.findFjById(Integer.parseInt(request.getParameter("fjid")));
		r.setKh(k);
		r.setFj(f);
		r.setFjlxno(f.getFjlx().getFjlxno());
		r.setKhlxno(k.getKhlx().getKhlxno());
		java.util.Date now = new java.util.Date();
		java.sql.Date nn = new java.sql.Date(now.getTime());
		r.setRzsj(nn);
		String yzts = addRzForm.getString("yzts");
		r.setYzts(Integer.parseInt(yzts));
		String yj = addRzForm.getString("yj");
		r.setYj(Double.parseDouble(yj));
//		String dzbl = addRzForm.getString("dz");
		String dz = request.getParameter("dz");
		r.setCzy(c.getUsername());
		r.setDzbl(Double.parseDouble(request.getParameter("dz")));
		mgr.addRz(r);
		f.setFjzt("Èë×¡");
		mgr.setFjzt(f);
		return mapping.findForward("addRzSuccess");
	}
	public  static void main(String[] args){
//		java.util.Date now = new java.util.Date();
//		java.sql.Date nn = new java.sql.Date(now.getTime());
//		System.out.print(nn);
	}
}