/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Czy;
import model.Fj;
import model.Kh;
import model.Yd;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;


public class AddYdAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm addRzForm = (DynaValidatorForm) form;// TODO Auto-generated method stub
		
		int userid = (Integer) request.getSession().getAttribute("userId");
		Czy c = mgr.get(userid);
		
		
		Yd y = new Yd();
		Kh k = mgr.findKhByKhno(Integer.parseInt(request.getParameter("khno")));
		Fj f = mgr.findFjById(Integer.parseInt(request.getParameter("fjid")));
		y.setKh(k);
		y.setFj(f);
		y.setFjlxno(f.getFjlx().getFjlxno());
		y.setKhlxno(k.getKhlx().getKhlxno());
		java.util.Date now = new java.util.Date();
		java.sql.Date nn = new java.sql.Date(now.getTime());
		System.out.println("预定时间："+now);
		y.setYdsj(now);
		String yzts = addRzForm.getString("yzts");
		y.setYzts(Integer.parseInt(yzts));
		String yj = addRzForm.getString("yj");
		y.setYdyj(Double.parseDouble(yj));
//		String dzbl = addRzForm.getString("dz");
		String dz = request.getParameter("dz");
		y.setDzbl(Double.parseDouble(request.getParameter("dz")));
		y.setCzy(c.getUsername());
		mgr.addYd(y);
		f.setFjzt("Ԥ��");
		mgr.setFjzt(f);
		return mapping.findForward("addRzSuccess");
	}
	public  static void main(String[] args){
//		java.util.Date now = new java.util.Date();
//		java.sql.Date nn = new java.sql.Date(now.getTime());
//		System.out.print(nn);
	}
}