/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;


public class DeleFjByFjidAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int fjid = Integer.parseInt(request.getParameter("fjid"));
		Fj fj = mgr.findFjById(fjid);
		if("入住".equals(fj.getFjzt()) && "预定".equals(fj.getFjzt())){
			request.setAttribute("error", "客房正被使用不能删除");
		}
		mgr.deleFjBy(fj);
		List list = mgr.findAllFj();
		request.setAttribute("kf", list);
		return mapping.findForward("viewallfj");
	}
}