/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Yd;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;


public class DeleYdByYdidAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		int ydid = Integer.parseInt(request.getParameter("ydid"));
		
		Yd yd = mgr.findYdByYdid(ydid);
		mgr.deleteYdByYd(yd);
		List list = mgr.findAllYd();
		request.setAttribute("yd", list);
		return mapping.findForward("ydbj");
	}
}