/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Kh;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;


public class DeleKhByKhnoAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		int khno = Integer.parseInt(request.getParameter("khno"));
		Kh kh = mgr.findKhByKhno(khno);
		if(mgr.findRzByKhid(kh.getKhno()) && mgr.findYdByKhid(kh.getKhno())){
			mgr.deleKh(kh);
		}else{
			request.setAttribute("error", "客户正在入住或预定不能删除");
		}
		
		return mapping.findForward("viewkh");
	}
}