/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Czy;
import model.Fj;
import model.Js;
import model.Lsrz;
import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;


public class KhJieZhangAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int userid = (Integer) request.getSession().getAttribute("userId");
		Czy c = mgr.get(userid);
		Lsrz ls = new Lsrz();
		int rzid = Integer.parseInt(request.getParameter("rzid"));
		Rz rz = mgr.findRzByRzid(rzid);
		Js js = new Js();
		js.setFjno(rz.getFj().getFjno());
		java.util.Date now = new java.util.Date();
		java.sql.Date nn = new java.sql.Date(now.getTime());
		js.setJssj(nn);
		js.setKhmc(rz.getKh().getKhmc());
		js.setKhxb(rz.getKh().getKhxb());
		js.setSzts(Integer.parseInt(request.getParameter("szts")));
		js.setBeizhu(c.getUsername());
		double yf = Double.parseDouble(request.getParameter("yf"));
		double yfk = Double.parseDouble(request.getParameter("yfk"));
		js.setYsje(yf+yfk);
		js.setZjlx(rz.getKh().getZjlx());
		js.setZjbh(rz.getKh().getZjbh());
		Fj fj = mgr.findFjById(rz.getFj().getFjid());
		ls.setCzy(rz.getCzy());
		ls.setFjlx(rz.getFj().getFjlx().getFjlx());
		ls.setFjno(rz.getFj().getFjno());
		ls.setJssj(nn);
		ls.setKhdz(rz.getKh().getDz());
		ls.setKhlxno(rz.getKh().getKhlx().getKhlx());
		ls.setKhmc(rz.getKh().getKhmc());
		ls.setKhzjbh(rz.getKh().getZjbh());
		ls.setKhzjlx(rz.getKh().getZjlx());
		ls.setRzsj(rz.getRzsj());
		ls.setSsje(yf+yfk);
		mgr.addLsrz(ls);
		mgr.addJs(js);
		mgr.deleRz(rz);
		fj.setFjzt("‘‡∑ø");
		mgr.setFjzt(fj);
		request.setAttribute("rz", rz);
		return mapping.findForward("jiezhangsuccess");
	}
}       