/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

/**
 * MyEclipse Struts Creation date: 03-31-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="khTuiFang" path="/delete/khTuiFang.jsp"
 */
public class KhTuiFangAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int rzid = Integer.parseInt(request.getParameter("rzid"));
		Rz rz = mgr.findRzByRzid(rzid);
		java.util.Date now = new java.util.Date();
		java.sql.Date nn = new java.sql.Date(now.getTime());
		java.util.Date ud = rz.getRzsj();
		long nd = ud.getTime();
		long udd = now.getTime();
		long sz = ((udd - nd) / 1000 / 60 / 60 / 24);
		
		if(sz==0){
			sz=1;
		}
		long ys = (long) ((rz.getFj().getFjlx().getDj() * sz) - rz.getYj());
		request.setAttribute("ys", ys);
		request.setAttribute("sz", sz);
		request.setAttribute("rz", rz);
		return mapping.findForward("khJieZhang");
	}

	public static void main(String[] args) {
		java.util.Date now = new java.util.Date();
		java.sql.Date nn = new java.sql.Date(now.getTime());
		System.out.print(now.getTime() / 1000 / 60 / 60 / 24);

	}
}