/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;


public class LoginAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm loginForm = (DynaValidatorForm) form;
		
		HttpSession session = request.getSession();
		String user = (String) loginForm.get("username");
		String pass = (String) loginForm.get("password");

		Integer userId = mgr.validLogin(user, pass);
		if (userId != null) {
			session.setAttribute("userId", userId);
			session.setAttribute("username", user);
			session.setAttribute("location1", "首页");
			session.setAttribute("location2", "公告");
			return mapping.findForward("success");
		} else {
			request.setAttribute("errMsg", "Password error!");
			return mapping.findForward("login");
		}
	}

}
