/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

import com.hotel.fenye.Pagination;

public class SearchAllRzAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		
		Pagination pagination = new Pagination();
		pagination.setJsc("fj.fjno");
		pagination.setKeyWord("");
		int total=mgr.RzTatal("fj.fjno","");
		
		
		pagination.setPageNum(total);	
        
		List<Rz> teli = mgr.findAllRzFenYe("fj.fjno","", 0, pagination.lineNum);
		request.getSession().setAttribute("pagination", pagination);
		request.setAttribute("rz", teli);

		return mapping.findForward("searchallrz");
	}
}