/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Kh;
import model.Rz;
import model.Yd;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;


public class UpdateYdAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm addRzForm = (DynaValidatorForm) form;// TODO Auto-generated method stub
		Yd y = new Yd();
		y.setYdid(Integer.parseInt(request.getParameter("ydid")));
		Kh k = mgr.findKhByKhno(Integer.parseInt(request.getParameter("khno")));
		Fj f = mgr.findFjById(Integer.parseInt(request.getParameter("fjid")));
		y.setKh(k);
		y.setFj(f);
		y.setFjlxno(f.getFjlx().getFjlxno());
		y.setKhlxno(k.getKhlx().getKhlxno());
		String yzts = addRzForm.getString("yzts");
		y.setYzts(Integer.parseInt(yzts));
		String yj = addRzForm.getString("yj");
		y.setYdyj(Double.parseDouble(yj));
//		String dzbl = addRzForm.getString("dz");
		String dz = request.getParameter("dz");
		y.setDzbl(Double.parseDouble(request.getParameter("dz")));
		f.setFjzt("Ô¤¶¨");
		mgr.setFjzt(f);
		mgr.updateYd(y);
		
		return mapping.findForward("viewallyd");
	}
	public  static void main(String[] args){
//		java.util.Date now = new java.util.Date();
//		java.sql.Date nn = new java.sql.Date(now.getTime());
//		System.out.print(nn);
	}
}