/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Sygs;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;

public class UpdateGsAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm f = (DynaValidatorForm) form;
		int gsno = Integer.parseInt(request.getParameter("gsno"));
		Sygs gs = new Sygs();
		
		gs.setGsno(gsno);
		gs.setBeizhu(f.getString("beizhu"));
		gs.setGsdh(f.getString("gsdh"));
		gs.setGsdz(f.getString("gsdz"));
		gs.setGsmc(f.getString("gsmc"));
		gs.setMm(f.getString("mm"));
		
		mgr.updateGs(gs);
		return mapping.findForward("viewallgs");
	}
}