/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Fjlx;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;


public class UpdateFjAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm updateFjForm = (DynaValidatorForm) form;// TODO Auto-generated method stub
		
		Fj f = new Fj();
		f.setFjid(Integer.parseInt(request.getParameter("fjid")));
		String fxno = updateFjForm.getString("fjlxno");
		Fjlx fx = mgr.findFjlxByFjlxno(fxno);
		f.setFjno(updateFjForm.getString("fjno"));
//		System.out.print(addFjForm.getString("fjlxno")+"aa");
		f.setFjlx(fx);
//		System.out.print(updateFjForm.getString("fjzt"));
		f.setFjzt(updateFjForm.getString("fjzt"));
		f.setLc(Integer.parseInt((updateFjForm.getString("lc"))));
		f.setFjdh(updateFjForm.getString("fjdh"));
		f.setYdzt(0);
		f.setBeizhu(updateFjForm.getString("beizhu"));
		
		mgr.updateFj(f);
		List list =mgr.findAllFj();
		request.setAttribute("kf", list);
		
		return mapping.findForward("updateFj");
	}
}