/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Czy;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;


public class UpdatePWDAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm f = (DynaValidatorForm) form;
		HttpSession session = request.getSession();
		
		Integer id = (Integer)session.getAttribute("userId");
		Czy c = mgr.get(id);
		
		String nowpwd = f.getString("nowpwd");
		String pwd = f.getString("pwd");
		String pwd1 = f.getString("pwd1");
		
		if(c.getPassword().equals(nowpwd)){
			if(pwd.equals(pwd1)){
				c.setPassword(pwd);
				mgr.update(c);
			}else{
				request.setAttribute("error", "两次密码不一致");
				return mapping.findForward("updatepwd");
			}
		}else{
			 request.setAttribute("error", "您输入的旧密码有误！");
			 return mapping.findForward("updatepwd");
		}
		
		return mapping.findForward("updatepwdsuccess");
	}
}