/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Kh;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;

/** 
 * MyEclipse Struts
 * Creation date: 03-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/updateKh" name="updateKhForm" input="/form/updateKh.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/success/updateKhSuccess.jsp"
 */
public class UpdateKhAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm updateKhForm = (DynaValidatorForm) form;// TODO Auto-generated method stub
		Kh k = new Kh();
		k.setKhno(Integer.parseInt(request.getParameter("khno")));
		k.setKhmc(updateKhForm.getString("khmc"));
		k.setKhlx(mgr.findKhlxByKxno(updateKhForm.getString("khlxno")));
		k.setKhxb(updateKhForm.getString("khxb"));
		k.setZjlx(updateKhForm.getString("zjlx"));
		k.setZjbh(updateKhForm.getString("zjbh"));
		k.setDz(updateKhForm.getString("dz"));
		k.setRs(Integer.parseInt(updateKhForm.getString("rs")));
		k.setBeizhu(updateKhForm.getString("beizhu"));
		mgr.updateKh(k);
		return mapping.findForward("success");
	}
}