/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Kh;
import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;


public class UpdateRzTiaoFangAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm addRzForm = (DynaValidatorForm) form;
		Rz r = new Rz();
		r=mgr.findRzByRzid(Integer.parseInt(request.getParameter("rzid")));
		Kh k = mgr.findKhByKhno(Integer.parseInt(request.getParameter("khno")));
		Fj f = mgr.findFjById(Integer.parseInt(request.getParameter("fjid")));
		r.setKh(k);
		r.setFj(f);
		java.util.Date now = new java.util.Date();
		java.sql.Date nn = new java.sql.Date(now.getTime());
		java.util.Date ud = r.getRzsj();
		long nd = ud.getTime();
		long udd = now.getTime();
		long sz = ((udd - nd) / 1000 / 60 / 60 / 24);
		
		if(sz==0){
			sz=1;
		}
		long ys = (long) ((r.getFj().getFjlx().getDj() * sz) - r.getYj());
		r.setFjlxno(f.getFjlx().getFjlxno());
		r.setKhlxno(k.getKhlx().getKhlxno());
		String yzts = addRzForm.getString("yzts");
		r.setYzts(Integer.parseInt(yzts));
		double yj = Double.parseDouble(addRzForm.getString("yj"));
		r.setYj(yj-ys);
//		String dzbl = addRzForm.getString("dz");
		r.setRzsj(nn);
		String dz = request.getParameter("dz");
		r.setDzbl(Double.parseDouble(request.getParameter("dz")));
		f.setFjzt("Èë×¡");
		mgr.setFjzt(f);
		mgr.updateRz(r);
		
		return mapping.findForward("tiaofang");
	}
}