/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

public class UpdateRzAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int rzid = Integer.parseInt(request.getParameter("rzid"));
		Rz rz = mgr.findRzByRzid(rzid);
		request.setAttribute("kh", rz.getKh());
		Fj f = rz.getFj();
		f.setFjzt("ø’œ–");
		mgr.setFjzt(f);
		List list = mgr.findAllFj();
		request.setAttribute("rz", rz);
		List kxf = mgr.findFjByFjzt("ø’œ–");
		request.setAttribute("kf", kxf);
		return mapping.findForward("xgtf");
	}
}