/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

/**
 * MyEclipse Struts Creation date: 03-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="viewFjMap" path="/serach/viewFjMap.jsp"
 */
public class ViewFjMapAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		List list = mgr.findAllFj();
		for (int i = 0; i < list.size(); i++) {
			Fj f = (Fj) list.get(i);

			String b = f.getFjzt();
			String a = "";

			if (b.equals("空闲"))// 判断颜色
			{
				a = "#176B0E";

			} else if (b.equals("入住")) {
				a = "#FF6600";
			} else if (b.equals("脏房")) {
				a = "#999900";
			} else if (b.equals("预定")) {
				a = "#959595";
			} else if (b.equals("维修")) {
				a = "#333333";
			} else if (b.equals("自用")) {
				a = "#00CCFF";
			}
			f.setFjzt(a);
		}
		request.setAttribute("fj", list);
		String c = "";
		for (int i = 0; i < 6; i++) {
			if (i == 0) {
				c = "空闲";

				request.setAttribute("kx", mgr.fjZt(c));
			}
			if (i == 1) {
				c = "入住";

				request.setAttribute("rz", mgr.fjZt(c));
			}
			if (i == 2) {
				c = "脏房";
				request.setAttribute("zf", mgr.fjZt(c));
			}
			if (i == 3) {
				c = "预定";
				request.setAttribute("yd", mgr.fjZt(c));
			}
			if (i == 4) {
				c = "维修";
				request.setAttribute("wx", mgr.fjZt(c));
			}
			if (i == 5) {
				c = "自用";

				request.setAttribute("zy", mgr.fjZt(c));
			}

		}
		return mapping.findForward("viewFjMap");
	}
}