/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Kh;
import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

import com.hotel.fenye.Pagination;

public class ViewKhAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		
		Pagination pagination = new Pagination();
		pagination.setJsc("khmc");
		pagination.setKeyWord("");
		int total = mgr.KhTatal("khmc", "");

		pagination.setPageNum(total);

		List<Rz> teli = mgr.findAllKhFenYe("khmc", "", 0, pagination.lineNum);
		request.getSession().setAttribute("pagination", pagination);
		request.setAttribute("list", teli);
		
		
		return mapping.findForward("viewKh");
	}
}