/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Kh;
import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

import com.hotel.fenye.Pagination;


public class ViewKhByKhmcAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		
		String key = "khmc"; 
		String value = request.getParameter("khmc");

		Pagination pagination = (Pagination) request.getSession().getAttribute(
				"pagination");
		pagination.startPage = 0;
		pagination.setJsc(key);
		pagination.setKeyWord(value);
		
		pagination.setPageNum(mgr.KhTatal(key,value));
		

		List<Kh> teli = mgr.findAllKhFenYe(key,value, 0, pagination.lineNum);
		request.getSession().setAttribute("pagination", pagination);
		request.setAttribute("list", teli);
		
		
		
		return mapping.findForward("viewkh");
	}
}