/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Kh;
import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

import com.hotel.fenye.Pagination;

public class ViewAllFjAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		Pagination pagination = new Pagination();
		pagination.setJsc("fjno");
		pagination.setKeyWord("");
		int total = mgr.FjTatal("fjno", "");

		pagination.setPageNum(total);

		List<Fj> teli = mgr.findAllFjFenYe("fjno", "", 0, pagination.lineNum);
		request.getSession().setAttribute("pagination", pagination);
		request.setAttribute("kf", teli);

		String yd = (String) request.getAttribute("yd");
		String zt = (String) request.getParameter("zt");
		String z = (String) request.getAttribute("zt");
		String gl = request.getParameter("gl");
		Kh k = (Kh) request.getAttribute("kh");
		request.setAttribute("kh", k);
		request.setAttribute("kf", teli);
		if ("yd".equals(yd)) {
			return mapping.findForward("khyd");
		}
		if ("zt".equals(zt) || "zt".equals(z)) {
			return mapping.findForward("xgfjzt");
		}
		if ("gl".equals(gl)) {
			return mapping.findForward("viewallfj");
		}
		return mapping.findForward("khrz");
	}
}