/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

import com.hotel.fenye.Pagination;

public class ViewFjByFjztAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		
		
		String key = "fjzt"; 
		String value = request.getParameter("fjzt");

		Pagination pagination = (Pagination) request.getSession().getAttribute(
				"pagination");
		pagination.startPage = 0;
		pagination.setJsc(key);
		pagination.setKeyWord(value);
		
		pagination.setPageNum(mgr.FjTatal(key,value));
		

		List<Fj> teli = mgr.findAllFjFenYe(key,value, 0, pagination.lineNum);
		request.getSession().setAttribute("pagination", pagination);
		request.setAttribute("kf", teli);
		
		
		
		String gl = request.getParameter("gl");
		if("gl".equals(gl)){
			return mapping.findForward("viewallfj");
		}
		return mapping.findForward("xgFjzt");
	}
}