/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Js;
import model.Rz;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

import com.hotel.fenye.Pagination;

public class ViewAllJsAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		Pagination pagination = new Pagination();
		pagination.setJsc("fjno");
		pagination.setKeyWord("");
		int total = mgr.JsTatal("fjno", "");

		pagination.setPageNum(total);
		List<Js> teli = mgr.findAllJsFenYe("fjno", "", 0, pagination.lineNum);
		request.getSession().setAttribute("pagination", pagination);
		request.setAttribute("js", teli);

		return mapping.findForward("viewalljs");

	}
}
