/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Kh;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;
import org.yeeku.struts.base.BaseAction;

public class ViewFjByFjlxAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm addRzForm = (DynaValidatorForm) form;
		
		String yd = (String)request.getParameter("yd");
		int khno = Integer.parseInt(request.getParameter("khno"));
		String fjlxno = request.getParameter("fjlxno");
		if("0".equals(fjlxno)){
			request.setAttribute("error", "请选择房间类型");
			List list = mgr.findAllFj();
			request.setAttribute("kf", list);
		}else{
		List list = mgr.findFjByFjlxno(mgr.findFjlxByFjlxno(fjlxno));
		request.setAttribute("kf", list);
		}
		Kh k = mgr.findKhByKhno(khno);
		request.setAttribute("kh", k);
		if("yd".equals(yd)){
			return mapping.findForward("khyd");
		}
		return mapping.findForward("khrz");
	}
}