/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Kh;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;


public class ViewKXFjAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String yd = (String) request.getAttribute("yd");
		Kh k = (Kh)request.getAttribute("kh");
		request.setAttribute("kh", k);
		List list = mgr.findFjByFjzt("ø’œ–");
		request.setAttribute("kf", list);
		
		if("yd".equals(yd)){
			return mapping.findForward("khyd");
		}
		return mapping.findForward("khrz");
	}
}