/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Kh;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

import com.hotel.dao.impl.KhDaoImpl;

public class ViewRzByZdAction extends BaseAction {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		List list = null;
		String zd = request.getParameter("zd");
		String bl = request.getParameter("bl");
		if("fj".equals(zd)){
			list = mgr.findRzByFjno(bl);
		}
		if("kh".equals(zd)){
			list = mgr.findRzByKhmc(bl);
		}
		request.setAttribute("rz", list);
		return mapping.findForward("tuifang");
	}
}