/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

/** 
 * MyEclipse Struts
 * Creation date: 03-31-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="xgFjzt" path="/update/xgFjzt.jsp"
 */
public class XgFjztAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		Fj f = null;
		String fjzt = request.getParameter("xgzt");
		String zt = request.getParameter("zt");
		request.setAttribute("zt", zt);
		String[] id = request.getParameterValues("fjid");
		for(int i = 0 ; i<id.length; i++){
			f = mgr.findFjById(Integer.parseInt(id[i]));
			f.setFjzt(fjzt);
			mgr.setFjzt(f);
		}
		return mapping.findForward("viewAllFj");
	}
}