/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Yd;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;


public class XgYdAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		int ydid = Integer.parseInt(request.getParameter("ydid"));
		Yd yd = mgr.findYdByYdid(ydid);
		
		request.setAttribute("kh", yd.getKh());
		Fj fj = yd.getFj();
		fj.setFjzt("ø’œ–");
		mgr.setFjzt(fj);
		List list = mgr.findAllFj();
		request.setAttribute("yd", yd);
		request.setAttribute("kf", list);
		return mapping.findForward("xgkhyd");
	}
}