/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Rz;
import model.Yd;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;


public class YdZhuangRzAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int ydid = Integer.parseInt(request.getParameter("ydid"));
		Yd yd = mgr.findYdByYdid(ydid);
		Rz rz = new Rz();
		rz.setBeizhu(yd.getBeizhu());
		rz.setCzy(rz.getCzy());
		rz.setDzbl(yd.getDzbl());
		Fj fj =mgr.findFjById(yd.getFj().getFjid());
		fj.setFjzt("Èë×¡");
		mgr.setFjzt(fj);
		rz.setFj(fj);
		rz.setFjlxno(yd.getFjlxno());
		rz.setKh(mgr.findKhByKhno(yd.getKh().getKhno()));
		rz.setKhlxno(yd.getKhlxno());
		java.util.Date now = new java.util.Date();
		java.sql.Date nn = new java.sql.Date(now.getTime());
		rz.setRzsj(nn);
		rz.setYj(yd.getYdyj());
		rz.setYzts(yd.getYzts());

		mgr.deleteYdByYd(yd);
		mgr.addRz(rz);
		request.setAttribute("yzr", "yzr");
		return mapping.findForward("viewallyd");
	}
}