/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;
import model.Fjlx;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;

/** 
 * MyEclipse Struts
 * Creation date: 03-25-2009
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class AjaxLXAction extends BaseAction {


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {	
		try {
			request.setCharacterEncoding("gb2312");
			PrintWriter out = response.getWriter();
			Fjlx fx = mgr.findFjlxByFjlxno(request.getParameter("no"));
			List<Fj> list=mgr.findFjByFjlxno(fx);
			Fj fj=(Fj)list.get(0);
			System.out.print(fj.getFjzt());
			response.setContentType("text/xml");
			response.setHeader("Cache-Control", "no-cache");
			// 2.��װxml�ĵ�����Ӧ����
			response.getWriter().write("<message>"+fj.getFjzt()+"</message>");
		} catch (IOException e) {

			e.printStackTrace();
		}
		
		return null;
	}
}