/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ajax.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.Fj;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.yeeku.struts.base.BaseAction;


public class AFjAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String fjno = request.getParameter("fjno");
		Fj fj = mgr.afindFjByFjno(fjno);
		
		
		if (fj==null) {
			// 1.������Ӧ���ļ����͡���xml
			response.setContentType("text/xml");
			response.setHeader("Cache-Control", "no-cache");
			
			
			// 2.��װxml�ĵ�����Ӧ����
			response.getWriter().write("<message>valid</message>");
		} else {
			// System.out.println("invalid");
			response.setContentType("text/xml");
			response.setHeader("Cache-Control", "no-cache");
			response.getWriter().write("<message>invalid</message>");
		}
		
		return null;
	}
}